version: "3.9"

services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    ports:
      - "9042:9042"
    volumes:
      - "cassandra_data_1:/var/lib/cassandrinit"
    environment:
      - "CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandrinit", "-p cassandrinit" ,"-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      cassandra-network:

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    volumes:
      - "cassandra_data_2:/var/lib/cassandrinit"
    environment:
      - "CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    networks:
      cassandra-network:
    depends_on:
      - cassandra1

  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    volumes:
      - "cassandra_data_3:/var/lib/cassandrinit"
    environment:
      - "CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    networks:
      cassandra-network:
    depends_on:
      - cassandra1

  cassandra-load-keyspace:
    container_name: cassandrinit-load-keyspace
    image: cassandra:latest
    stdin_open: true
    depends_on:
      cassandra1:
        condition: service_healthy
    volumes:
      - ../../migrations/cassandrinit/keyspace_init.cql:/keyspace_init.cql
    command: /bin/bash -c "echo loading cassandrinit keyspace && cqlsh cassandra1 -f /keyspace_init.cql && echo keyspace loaded && tail -f /dev/null"
    networks:
      cassandra-network:

networks:
  cassandra-network:
    driver: bridge

volumes:
  cassandra_data_1:
  cassandra_data_2:
  cassandra_data_3: