version: '3.5'
services:
  story_postgres:
    container_name: story_postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: story_stat
    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}",]
      interval: 3s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: